In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from glob import glob
import matplotlib.pyplot as plt

%matplotlib inline

In [22]:
h=tf.constant("Hello")
f=tf.constant("World")
hf=h+f
print("hf:",hf)
with tf.Session() as session:
    ans=session.run(hf)
    print(ans,type(ans),ans.decode("utf-8"))

hf: Tensor("add_10:0", shape=(), dtype=string)
b'HelloWorld' <class 'bytes'> HelloWorld


In [48]:
a=tf.constant(5,name='a')
b=tf.constant(6)
c=tf.constant(7)

d=a*b
e=tf.add(d,b)
f=tf.subtract(d,e)

session=tf.Session()
print(session.run(f))
print(tf.Graph())
print(tf.get_default_graph())
print(f.graph)

-6


In [25]:
g1 = tf.get_default_graph()
g2 = tf.Graph()
print(g1 is tf.get_default_graph())
with g2.as_default():
    print(g1 is tf.get_default_graph(), g2 is tf.get_default_graph())
print(g1 is tf.get_default_graph())

True
False True
True


In [29]:
g1 = tf.Graph()
g2 = tf.Graph()
with g1.as_default():
    c1 = tf.constant(4.0)

with g2.as_default():
    c2 = tf.constant(2.0)

c=c1+c2
with tf.Session() as session:
    session.run(c)

ValueError: Tensor("Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("Const:0", shape=(), dtype=float32).

In [31]:
c1,c2

(<tf.Tensor 'Const:0' shape=() dtype=float32>,
 <tf.Tensor 'Const:0' shape=() dtype=float32>)

In [30]:
fetchers = [a, b, c, d, e, f]
session.run(fetchers)

[5, 6, 7, 30, 36, -6]

In [34]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
c

<tf.Tensor 'Const_34:0' shape=(2, 3) dtype=int32>

In [35]:
c = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]))
c

<tf.Tensor 'Const_35:0' shape=(2, 3) dtype=int32>

In [37]:
c = tf.constant(4, dtype='float64')
c.dtype

tf.float64

In [38]:
c = tf.ones((4, 3))
session.run(c)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [40]:
c = tf.fill((4, 3), 2)
session.run(c)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [41]:
c=tf.random_normal((2,3),0,2)
session.run(c)

array([[-3.83514  ,  1.1112695, -2.2636116],
       [-0.3758555, -1.4098092, -0.8282148]], dtype=float32)

In [42]:
c=tf.truncated_normal((2,3),0,2)
session.run(c)

array([[-0.79716766, -1.9505113 ,  2.6285305 ],
       [ 3.5492625 ,  0.7962213 ,  3.3329022 ]], dtype=float32)

In [44]:
c=tf.random_uniform((2,3),seed=100)
session.run(c)

array([[0.9617498 , 0.44918132, 0.5127076 ],
       [0.8348917 , 0.54734325, 0.8099698 ]], dtype=float32)

In [45]:
c = tf.linspace(0.2, 0.3, 5)
print(c.get_shape())
session.run(c)

(5,)


array([0.2       , 0.22500001, 0.25      , 0.275     , 0.3       ],
      dtype=float32)

In [46]:
c = tf.range(0.4, 5.0, 0.25)
print(c.get_shape())
session.run(c)

(19,)


array([0.4 , 0.65, 0.9 , 1.15, 1.4 , 1.65, 1.9 , 2.15, 2.4 , 2.65, 2.9 ,
       3.15, 3.4 , 3.65, 3.9 , 4.15, 4.4 , 4.65, 4.9 ], dtype=float32)

In [50]:
X = tf.random_normal((5, 10), mean = 0.0, stddev = 1.0, seed = 0)
w = tf.random_normal((10, 1), mean = 0.0, stddev = 1.0, seed = 0)
b = tf.fill((5, 1), 1.0) # Create tensors of a given value
s = tf.sigmoid(tf.matmul(X,w) - b)
session.run(s)

array([[0.9999913 ],
       [0.14483425],
       [0.9941877 ],
       [0.55156505],
       [0.9913591 ]], dtype=float32)

In [51]:
c = tf.constant(15, name = "c")
x = tf.Variable(c * 5, name = "x")
init = tf.global_variables_initializer()
session.run(init)
session.run(x)

75

In [52]:
X_data = np.random.randn(5, 10)
w_data = np.random.randn(10, 1)

X = tf.placeholder("float32", shape=(5, 10))
w = tf.placeholder("float32", shape=(10, 1))
b = tf.fill((5, 1), - 1.0)
s = tf.sigmoid(tf.matmul(X, w) + b)

session.run(s, feed_dict={X: X_data, w: w_data})

array([[0.99064964],
       [0.39502385],
       [0.06153277],
       [0.76034594],
       [0.8290465 ]], dtype=float32)

In [60]:
tf.reset_default_graph()

with tf.Session() as sess:
    W = tf.Variable(3.0, dtype=tf.float32, name = "W")
    W = W.assign(W+1)
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    saver = tf.train.Saver()
    saver.save(sess, "./model1.ckpt")

4.0


In [61]:
import tensorflow as tf
tf.reset_default_graph()
W1 = tf.Variable(3.0, dtype=tf.float32, name = "W")

with tf.Session() as sess:
    saver = tf.train.Saver()
    saver.restore(sess, "./model1.ckpt")
    print(sess.run(W1))

INFO:tensorflow:Restoring parameters from ./model1.ckpt
4.0


In [79]:
n = (10 ** 7)


In [80]:
%%time 
np.sum(np.arange(n) ** 2)

Wall time: 508 ms


-1039031360

In [81]:

%%time
x = tf.placeholder(dtype=tf.int64)
y = tf.reduce_sum(tf.range(x) ** 2)
with tf.Session() as sess:
    print(sess.run(y, feed_dict={x: n}))

1291890006563070912
Wall time: 968 ms


In [82]:
kernel=tf.contrib.layers.variance_scaling_initializer()

In [83]:
with tf.Session() as sess:
    print(kernel)

<function variance_scaling_initializer.<locals>._initializer at 0x000001D3CD783D90>
